version: "3"

services:
  api-node-car:
    container_name: api-node-car
    build: .
    command: npm run start
    ports:
      - "3333:3333"
    working_dir: "/home/app/"
    volumes:
      - "./:/home/app/"
